language: node_js
sudo: true

dist: trusty

node_js:
  - "8"

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - YARN_VERSION: 1.7.0
    - NG_CLI_VERSION: 6.0.8

before_install:
  # Install latest yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"

  # Install @angular/cli
  - npm install -g @angular/cli@$NG_CLI_VERSION

  # install the dependencies and build the necessary files
  - cd test-app && yarn install && yarn build:browser && yarn build:server

script:
  # run the test script in the directory
  - cd ../test-app && yarn test


